apiVersion: v1
kind: Service
metadata:
  name: etcd-service-0
  labels:
    name: etcd-service-0
    etcd_node: etcd-0
spec:
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: server
      port: 2380
      protocol: TCP
      targetPort: 2380
    - name: etcd-4001
      port: 4001
      protocol: TCP
      targetPort: 4001
    - name: etcd-7001
      port: 7001
      protocol: TCP
      targetPort: 7001
  selector:
    etcd_node: etcd-0
