apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  labels:
    name: etcd-service
spec:
  ports:
    - name: etcd-2379
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: etcd-4001
      port: 4001
      protocol: TCP
      targetPort: 4001
    - name: etcd-7001
      port: 7001
      protocol: TCP
      targetPort: 7001
  selector:
    app: etcd-app
