apiVersion: v1
kind: Pod
metadata:
  name: etcd-app-0
  labels:
    name: etcd-app
    etcd_node: etcd-0
spec:
  containers:
    - command:
      - /usr/local/bin/etcd
      - --name
      - etcd-0
      - --initial-advertise-peer-urls
      - http://etcd-service-0:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://etcd-service-0:2379
      - --initial-cluster
      - etcd-0=http://etcd-service-0:2380,etcd-1=http://etcd-service-1:2380,etcd-2=http://etcd-service-2:2380
      - --initial-cluster-state
      - new
      image: quay.io/coreos/etcd:latest
      name: etcd-app-0
      ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
        - containerPort: 4001
          protocol: TCP
        - containerPort: 7001
          protocol: TCP
  restartPolicy: Never
  nodeSelector:
    name: minikube
