apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
spec:
  ports:
    - port: 3306
      name: mysql-port-0
      targetPort: 3306
      protocol: TCP
    - port: 4567
      name: mysql-port-1
      targetPort: 4567
      protocol: TCP
  clusterIP: None
  selector:
    app: mysql-app
